const Car = require('../models/car.model')
const carData = [
  {
    make: "Toyota",
    model: "Camry",
    year: 2020,
    hourlyRate: 10,
    dailyRate: 50,
    availableQuantity: 5,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "Silver",
    mileage: 30,
    engineSize: 2.5,
    registrationNumber: "ABC123",
    insuranceProvider: "ABC Insurance",
    isAvailable: true,
    image:"asdf.jpg"
  },
  {
    make: "Honda",
    model: "Accord",
    year: 2019,
    hourlyRate: 12,
    dailyRate: 60,
    availableQuantity: 3,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "White",
    mileage: 28,
    engineSize: 2.0,
    registrationNumber: "DEF456",
    insuranceProvider: "XYZ Insurance",
    isAvailable: false
  },
  {
    make: "Ford",
    model: "Mustang",
    year: 2021,
    hourlyRate: 15,
    dailyRate: 70,
    availableQuantity: 8,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 4,
    color: "Red",
    mileage: 25,
    engineSize: 5.0,
    registrationNumber: "GHI789",
    insuranceProvider: "PQR Insurance",
    isAvailable: true
  },
  {
    make: "Chevrolet",
    model: "Camaro",
    year: 2018,
    hourlyRate: 14,
    dailyRate: 65,
    availableQuantity: 6,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 4,
    color: "Black",
    mileage: 27,
    engineSize: 6.2,
    registrationNumber: "JKL012",
    insuranceProvider: "MNO Insurance",
    isAvailable: true
  },
  {
    make: "Nissan",
    model: "Altima",
    year: 2019,
    hourlyRate: 11,
    dailyRate: 55,
    availableQuantity: 4,
    fuelType: "Gasoline",
    transmission: "CVT",
    seatingCapacity: 5,
    color: "Blue",
    mileage: 29,
    engineSize: 2.5,
    registrationNumber: "MNO345",
    insuranceProvider: "PQR Insurance",
    isAvailable: true
  },
  // Add more car objects with relevant fields
  {
    make: "Toyota",
    model: "Corolla",
    year: 2018,
    hourlyRate: 9,
    dailyRate: 45,
    availableQuantity: 7,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "Gray",
    mileage: 32,
    engineSize: 1.8,
    registrationNumber: "PQR678",
    insuranceProvider: "XYZ Insurance",
    isAvailable: true
  },
  {
    make: "Honda",
    model: "Civic",
    year: 2020,
    hourlyRate: 11,
    dailyRate: 55,
    availableQuantity: 6,
    fuelType: "Gasoline",
    transmission: "CVT",
    seatingCapacity: 5,
    color: "Red",
    mileage: 30,
    engineSize: 2.0,
    registrationNumber: "STU901",
    insuranceProvider: "ABC Insurance",
    isAvailable: false
  },
  {
    make: "Ford",
    model: "Fusion",
    year: 2019,
    hourlyRate: 12,
    dailyRate: 60,
    availableQuantity: 9,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "Black",
    mileage: 28,
    engineSize: 2.5,
    registrationNumber: "VWX234",
    insuranceProvider: "MNO Insurance",
    isAvailable: true
  },
  {
    make: "Chevrolet",
    model: "Malibu",
    year: 2020,
    hourlyRate: 13,
    dailyRate: 65,
    availableQuantity: 5,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "White",
    mileage: 29,
    engineSize: 2.0,
    registrationNumber: "YZA567",
    insuranceProvider: "PQR Insurance",
    isAvailable: true
  },
  {
    make: "Nissan",
    model: "Sentra",
    year: 2017,
    hourlyRate: 10,
    dailyRate: 50,
    availableQuantity: 4,
    fuelType: "Gasoline",
    transmission: "CVT",
    seatingCapacity: 5,
    color: "Blue",
    mileage: 26,
    engineSize: 1.8,
    registrationNumber: "BCD890",
    insuranceProvider: "XYZ Insurance",
    isAvailable: false
  },
  {
    make: "Toyota",
    model: "Rav4",
    year: 2021,
    hourlyRate: 14,
    dailyRate: 70,
    availableQuantity: 8,
    fuelType: "Hybrid",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "Silver",
    mileage: 35,
    engineSize: 2.5,
    registrationNumber: "EFG123",
    insuranceProvider: "ABC Insurance",
    isAvailable: true
  },
  {
    make: "Honda",
    model: "Pilot",
    year: 2018,
    hourlyRate: 16,
    dailyRate: 80,
    availableQuantity: 3,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 8,
    color: "Gray",
    mileage: 24,
    engineSize: 3.5,
    registrationNumber: "HIJ456",
    insuranceProvider: "MNO Insurance",
    isAvailable: true
  },
  {
    make: "Ford",
    model: "Explorer",
    year: 2020,
    hourlyRate: 18,
    dailyRate: 90,
    availableQuantity: 6,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 7,
    color: "Black",
    mileage: 27,
    engineSize: 3.0,
    registrationNumber: "KLM789",
    insuranceProvider: "PQR Insurance",
    isAvailable: false
  },
  {
    make: "Chevrolet",
    model: "Tahoe",
    year: 2019,
    hourlyRate: 20,
    dailyRate: 100,
    availableQuantity: 5,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 8,
    color: "White",
    mileage: 23,
    engineSize: 5.3,
    registrationNumber: "NOP012",
    insuranceProvider: "XYZ Insurance",
    isAvailable: true
  },
  {
    make: "Nissan",
    model: "Pathfinder",
    year: 2021,
    hourlyRate: 22,
    dailyRate: 110,
    availableQuantity: 7,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 7,
    color: "Red",
    mileage: 25,
    engineSize: 3.5,
    registrationNumber: "QRS345",
    insuranceProvider: "ABC Insurance",
    isAvailable: true
  },
  {
    make: "Toyota",
    model: "Highlander",
    year: 2020,
    hourlyRate: 24,
    dailyRate: 120,
    availableQuantity: 4,
    fuelType: "Hybrid",
    transmission: "Automatic",
    seatingCapacity: 7,
    color: "Blue",
    mileage: 31,
    engineSize: 3.5,
    registrationNumber: "TUV678",
    insuranceProvider: "MNO Insurance",
    isAvailable: true
  },
  {
    make: "Honda",
    model: "Odyssey",
    year: 2017,
    hourlyRate: 26,
    dailyRate: 130,
    availableQuantity: 6,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 8,
    color: "White",
    mileage: 22,
    engineSize: 3.5,
    registrationNumber: "WXY901",
    insuranceProvider: "PQR Insurance",
    isAvailable: false
  },
  {
    make: "Ford",
    model: "Escape",
    year: 2018,
    hourlyRate: 28,
    dailyRate: 140,
    availableQuantity: 9,
    fuelType: "Hybrid",
    transmission: "Automatic",
    seatingCapacity: 5,
    color: "Silver",
    mileage: 33,
    engineSize: 2.5,
    registrationNumber: "YZA234",
    insuranceProvider: "ABC Insurance",
    isAvailable: true
  },
  {
    make: "Chevrolet",
    model: "Suburban",
    year: 2021,
    hourlyRate: 30,
    dailyRate: 150,
    availableQuantity: 5,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 8,
    color: "Black",
    mileage: 21,
    engineSize: 5.3,
    registrationNumber: "BCD567",
    insuranceProvider: "MNO Insurance",
    isAvailable: true
  },
  {
    make: "Nissan",
    model: "Armada",
    year: 2019,
    hourlyRate: 32,
    dailyRate: 160,
    availableQuantity: 3,
    fuelType: "Gasoline",
    transmission: "Automatic",
    seatingCapacity: 8,
    color: "Gray",
    mileage: 24,
    engineSize: 5.6,
    registrationNumber: "EFG890",
    insuranceProvider: "PQR Insurance",
    isAvailable: false
  }
];



const fun = async()=>{
  // image:'uploads/p5.jpg'
  carImage=["car1"]
    carData.map(car=>{
      let image = `car${Math.floor(Math.random()*15)}.png`
      car.image= image;
    Car.insertMany(car)
  })
    // await Car.insertMany(carData)
}
fun()
  